[package]
name = "api"
version = "0.1.0"
edition = "2021"

[dependencies]
docker_example = { path = "../docker_example" }
common = { path = "../common" }
db = { path = "../db" }
axum = "0.7"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
jsonwebtoken = "9"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["cors"] }
log = "0.4"
axum-extra = { version = "0.9", features = ["typed-header"] }
chrono = { version = "0.4", features = ["serde"] }
headers = "0.4"
validator = { version = "0.16", features = ["derive"] }
lazy_static = "1.4"
regex = "1.10"
sqlx = { version = "0.7", features = ["sqlite", "runtime-tokio-native-tls", "macros"] }