PY := python3

build:
	@echo "Nothing to build for Python."

task1: build
	$(PY) main.py task1

task2: build
	$(PY) main.py task2

task3: build
	$(PY) main.py task3

run: build
	$(PY) main.py task1
	$(PY) main.py task2
	$(PY) main.py task3

clean:
	@echo "Nothing to clean for Python."

.PHONY: build task1 task2 task3 run clean
