[workspace]
resolver = "3"
members = [
    "ai",
    "api", 
    "moss_parser",
    "code_manager",
    "code_runner",
    "common",
    "db",
    "marker",
    "migration",
    "seeder",
    "services"
]
