[config]
skip_core_tasks = true
default_to_workspace = false

[tasks.migrate]
description = "Run DB migrations and seed the DB"
script = ["cargo run -p migration"]

[tasks.clean]
description = "Delete DB file only"
script = ["cargo run -p migration -- clean"]

[tasks.fresh]
description = "Drop DB and re-run migrations (no seed)"
script = ["cargo run -p migration -- fresh"]

[tasks.seed]
description = "Seed the DB"
script = ["cargo run -p seeder --quiet"]

[tasks.fresh_seed]
description = "Drop DB, re-run migrations, then seed"
script = [
    "cargo make fresh",
    "cargo make seed"
]

[tasks.api]
description = "Run the API server"
script = ["cargo run -p api"]

[tasks.code]
description = "Run the Code Manager server"
script = ["cargo run -p code_manager"]
