[package]
name = "util"
version = "0.1.0"
edition = "2024"

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["std"] }
chrono = { version = "0.4", features = ["clock", "std"] }