[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
code-runner = { path = "../code_runner" }
services = { path = "../services" }
util = { path = "../util" }

rand = "0.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15"
serde_json = "1.0"
