[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
sqlx = { version = "0.7", features = [
    "sqlite",
    "runtime-tokio-native-tls",
    "macros",
] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
fake = "2"
once_cell = "1.18"
axum = "0.7"
tower = "0.4"
dotenvy = "0.15"
uuid = { version = "1.3", features = ["v4"] }
argon2 = "0.5.3"
