[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
once_cell = "1"
dotenvy = "0.15"
log = "0.4"
fern = "0.6"
chrono = "0.4"
colored = "2"
validator = { version = "0.16", features = ["derive"] }