use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use sea_orm::{ActiveValue::Set, DatabaseConnection, EntityTrait};
use std::env;
use std::fs;
use std::path::PathBuf;

/// Represents the output generated by a student's submission for an assignment task.
///
/// Each output is linked to a specific assignment, task, and submitting user.
/// Timestamps are included to track when the file was created and last updated.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "assignment_submission_outputs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub task_id: i64,
    pub submission_id: i64,
    pub path: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assignment_task::Entity",
        from = "Column::TaskId",
        to = "super::assignment_task::Column::TaskNumber"
    )]
    AssignmentTask,

    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::SubmissionId",
        to = "super::user::Column::Id"
    )]
    AssignmentSubmission,
}

impl ActiveModelBehavior for ActiveModel {}

impl Model {
    pub fn storage_root() -> PathBuf {
        env::var("ASSIGNMENT_STORAGE_ROOT")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from("data/assignment_files"))
    }

    pub fn full_directory_path(
        module_id: i64,
        assignment_id: i64,
        task_number: i64,
        user_id: i64,
        attempt_number: i64,
    ) -> PathBuf {
        Self::storage_root()
            .join(format!("module_{module_id}"))
            .join(format!("assignment_{assignment_id}"))
            .join("assignment_submissions")
            .join(format!("user_{user_id}"))
            .join(format!("attempt_{attempt_number}"))
            .join(format!("submission_output"))
            .join(format!("task_{task_number}"))
    }

    pub fn full_path(&self) -> PathBuf {
        Self::storage_root().join(&self.path)
    }

    pub async fn save_file(
        db: &DatabaseConnection,
        task_id: i64,
        submission_id: i64,
        filename: &str,
        bytes: &[u8],
    ) -> Result<Self, DbErr> {
        let now = Utc::now();

        let partial = ActiveModel {
            task_id: Set(task_id),
            submission_id: Set(submission_id),
            path: Set("".to_string()),
            created_at: Set(now),
            updated_at: Set(now),
            ..Default::default()
        };

        let inserted: Model = partial.insert(db).await?;

        let ext = PathBuf::from(filename)
            .extension()
            .map(|e| e.to_string_lossy().to_string());

        let stored_filename = match ext {
            Some(ext) => format!("{}.{}", inserted.id, ext),
            None => inserted.id.to_string(),
        };

        //Get submission
        let submission = super::assignment_submission::Entity::find_by_id(submission_id)
            .one(db)
            .await
            .map_err(|e| DbErr::Custom(format!("DB error finding task: {}", e)))?
            .ok_or_else(|| DbErr::Custom("Submission not found".to_string()))?;

        let assignment = super::assignment::Entity::find_by_id(submission.assignment_id)
            .one(db)
            .await
            .map_err(|e| DbErr::Custom(format!("DB error finding assignment: {}", e)))?
            .ok_or_else(|| DbErr::Custom("Assignment not found".to_string()))?;

        let module_id = assignment.module_id;

        let task = super::assignment_task::Entity::find_by_id(task_id)
            .one(db)
            .await
            .map_err(|e| DbErr::Custom(format!("DB error finding task: {}", e)))?
            .ok_or_else(|| DbErr::Custom("Task not found".to_string()))?;

        let dir_path = Self::full_directory_path(
            module_id,
            assignment.id,
            task.task_number,
            submission.user_id,
            submission.attempt,
        );
        fs::create_dir_all(&dir_path)
            .map_err(|e| DbErr::Custom(format!("Failed to create directory: {e}")))?;

        let file_path = dir_path.join(&stored_filename);
        let relative_path = file_path
            .strip_prefix(Self::storage_root())
            .unwrap()
            .to_string_lossy()
            .to_string();

        fs::write(&file_path, bytes)
            .map_err(|e| DbErr::Custom(format!("Failed to write file: {e}")))?;

        let mut model: ActiveModel = inserted.into();
        model.path = Set(relative_path);
        model.updated_at = Set(Utc::now());

        model.update(db).await
    }
}
