use chrono::{DateTime, Utc};
use sea_orm::entity::prelude::*;
use sea_orm::EntityTrait;

/// Represents the output generated by a student's submission for an assignment task.
///
/// Each output is linked to a specific assignment, task, and submitting user.
/// Timestamps are included to track when the file was created and last updated.
#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "assignment_submission_outputs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub task_id: i64,
    pub submission_id: i64,
    pub path: String,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::assignment_task::Entity",
        from = "Column::TaskId",
        to = "super::assignment_task::Column::Id"
    )]
    AssignmentTask,

    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::SubmissionId",
        to = "super::user::Column::Id"
    )]
    AssignmentSubmission,
}

impl ActiveModelBehavior for ActiveModel {}
impl Model {}