pub mod achievements;
pub mod achievement_progress;
pub mod announcements;
pub mod assignment;
pub mod assignment_file;
pub mod assignment_interpreter;
pub mod assignment_memo_output;
pub mod assignment_overwrite_file;
pub mod assignment_submission;
pub mod assignment_submission_output;
pub mod assignment_task;
pub mod attendance_record;
pub mod attendance_session;
pub mod module;
pub mod moss_report;
pub mod password_reset_token;
pub mod plagiarism_case;
pub mod system_metric;
pub mod ticket_messages;
pub mod tickets;
pub mod user;
pub mod user_module_role;

pub use achievements::Entity as Achievement;
pub use achievement_progress::Entity as AchievementProgress;
pub use announcements::Entity as Announcements;
pub use assignment::Entity as Assignment;
pub use assignment_file::Entity as AssignmentFile;
pub use assignment_interpreter::Entity as AssignmentInterpreter;
pub use assignment_memo_output::Entity as AssignmentMemoOutput;
pub use assignment_overwrite_file::Entity as AssignmentOverwriteFile;
pub use assignment_submission::Entity as AssignmentSubmission;
pub use assignment_submission_output::Entity as AssignmentSubmissionOutput;
pub use assignment_task::Entity as AssignmentTask;
pub use attendance_record::Entity as AttendanceRecord;
pub use attendance_session::Entity as AttendanceSession;
pub use module::Entity as Module;
pub use password_reset_token::Entity as PasswordResetToken;
pub use plagiarism_case::Entity as PlagiarismCase;
pub use system_metric::Entity as SystemMetric;
pub use ticket_messages::Entity as TicketMessages;
pub use tickets::Entity as Tickets;
pub use user::Entity as User;
pub use user_module_role::Entity as UserModuleRole;
