[package]
name = "code-runner"
version = "0.1.0"
edition = "2024"

[dependencies]
zip = "0.6"
uuid = { version = "1", features = ["v4"] }
tempfile = "3"
tokio = { version = "1", features = ["full"] }
